# Generated by Django 5.0.6 on 2024-08-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.TextField()),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.TextField()),
                ('gender', models.TextField()),
                ('experience', models.TextField()),
                ('address', models.TextField()),
                ('guardian', models.CharField(max_length=255)),
                ('guardian_phone_number', models.TextField()),
                ('person_ID', models.TextField()),
            ],
        ),
    ]
