# Generated by Django 5.0.6 on 2024-08-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_duration', models.TextField()),
                ('course_schedule', models.TextField()),
                ('course_level', models.TextField()),
                ('course_instructor', models.CharField(max_length=255)),
                ('course_requirement', models.TextField()),
                ('course_participant_count', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Record',
            new_name='User',
        ),
    ]
